apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ include "website.fullname" . }}-server'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      nodeSelector:
        workload: assets
      containers:
        - name: server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
          {{- end }}
          ports:
            - containerPort: 3000
