apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ include "website.fullname" . }}-server'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      nodeSelector:
        workload: assets
      {{- with .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      containers:
        - name: server
          image: "{{ .Values.image.full }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
          {{- end }}
          ports:
            - containerPort: 3000

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: '{{ include "website.fullname" . }}-server'
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: '{{ include "website.fullname" . }}-server'
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: '{{ include "website.fullname" . }}-ingress'
    namespace: { { .Release.Namespace } }
    annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        traefik.ingress.kubernetes.io/router.tls: 'true'
        traefik.ingress.kubernetes.io/router.tls.certresolver: myresolver
spec:
    rules:
        - host: { { .Values.domain } }
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: '{{ include "website.fullname" . }}-server'
                            port:
                                number: 80


---

apiVersion: v1
kind: Service
metadata:
  name: '{{ include "website.fullname" . }}-server'
spec:
  selector:
    app: server
  ports:
    - name: http
      port: 80
      targetPort: 3000
